In [26]:
#to install tensorflow open comd.prompt,pip install tensorflow then pip install keras, create new environment in anaconda navig-
#-ator, restart system, open conda navigator and new environment click on tensorflow,keras and tensorflow estimator and apply
#and then i have to install !pip install pandas in jupyter as it thrown me module not found error
!pip install sklearn
!pip install matplotlib

In [28]:
#importing libraries
import pandas as pd
import numpy as np
import tensorflow as tf


In [29]:
#datapreprocessing
dataset=pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [30]:
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [17]:
#No missing data in the dataset
#So now we need to encod categorical variables, for gender column there are only 2 elements so we use label encoding and 
#for more than 3 categories in a column we use OneHotencoder

In [31]:
#encoding gender column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [32]:
#column transformer transforms one column to 3
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
Xprint(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [33]:
#splitting the data into train set and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [34]:
#Feature scaling, irrespective of the data feature scaling is compulsory in deeplearning models
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#its a bit different than calssification and regression models, #no indexes used here
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [35]:
#Building the ANN
#intializing ANN

ann = tf.keras.models.Sequential()

In [36]:
#Adding the first input layer and the first hidden layer relu means rectifier activation function(rectifier linear unit full form)
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

In [37]:
#Addign second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

In [38]:
#Adding output layer
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid')) #here for non binary activation = 'softmax'

In [39]:
#Training the ANN Model, this can be done in 2 steps 1 Compiling 2 Training ANN on training set
ann.compile(optimizer = 'adam',loss='binary_crossentropy',metrics = ['accuracy'])#optimizer fixes SGD,loss gives loss function,
#for non binary classification predecting 3 different categories, loss = 'categorical_crossentropy'


In [40]:
#Training the ANN on Training set
ann.fit(X_train,y_train, batch_size= 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 925us/step - loss: 0.5738 - accuracy: 0.7505
Epoch 2/100
250/250 [==============================] - 0s 810us/step - loss: 0.4934 - accuracy: 0.7955
Epoch 3/100
250/250 [==============================] - 0s 778us/step - loss: 0.4590 - accuracy: 0.7972
Epoch 4/100
250/250 [==============================] - 0s 802us/step - loss: 0.4386 - accuracy: 0.8044
Epoch 5/100
250/250 [==============================] - 0s 772us/step - loss: 0.4290 - accuracy: 0.8070
Epoch 6/100
250/250 [==============================] - 0s 758us/step - loss: 0.4232 - accuracy: 0.8136
Epoch 7/100
250/250 [==============================] - 0s 837us/step - loss: 0.4186 - accuracy: 0.8186
Epoch 8/100
250/250 [==============================] - 0s 802us/step - loss: 0.4145 - accuracy: 0.8221
Epoch 9/100
250/250 [==============================] - 0s 808us/step - loss: 0.4095 - accuracy: 0.8238
Epoch 10/100
250/250 [==============================] - 0s 774us/step - l

#Making the predictions and evaluating the model
 Part 4 - Making the predictions and evaluating the model
Predicting the result of a single observation
Homework

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?

Solution

In [42]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
#without > 0.5 we get the probability

[[False]]


In [43]:
#predicting test results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1508   87]
 [ 201  204]]


0.856